logging:
  log_dir: "logs"

run:
  device: "cuda"

paths:
  repo_root: "D:/code/mcfp"
  train_config: "D:/code/mcfp/configs/train_stage1.yaml"
  checkpoint: "D:/code/mcfp/runs/stage1/exp_pose6d_v1/checkpoints/step_0200000.pt"
  morph_json: "D:/code/mcfp/data/morph_specs/franka/franka_base.json"

data:
  label_keys: []

query:
  # pose_mode: "rpy"
  # rpy_degrees: true
  # pose: [0.6211220026016235, 0.4455280900001526, 0.48473525047302246, 1.0, 0.0, 1.0]
  gws_threshold: 0.80
  pose_mode: "quat"
  pose: [0.02282588556408882, 0.7425815463066101, 0.2923544645309448, 0.87934809923172, -0.1413036584854126, 0.4534895122051239, 0.03357887268066406]

validation:
  enable: true
  verbose: true
  data_gen_config: "D:/code/mcfp/configs/data_gen_pose_ik_franka.yaml"
